services:
  ats:
    build:
      context: ../../../
      dockerfile: ./apps/ats/web/Dockerfile
      platforms:
        - "linux/amd64"
      args:
        REACT_APP_MIRROR_NODE: ${REACT_APP_MIRROR_NODE}
        REACT_APP_RPC_NODE: ${REACT_APP_RPC_NODE}
        REACT_APP_RPC_RESOLVER: ${REACT_APP_RPC_RESOLVER}
        REACT_APP_RPC_FACTORY: ${REACT_APP_RPC_FACTORY}
        # # Optional
        # REACT_APP_EQUITY_CONFIG_ID: ${REACT_APP_EQUITY_CONFIG_ID}
        # REACT_APP_EQUITY_CONFIG_VERSION: ${REACT_APP_EQUITY_CONFIG_VERSION}
        # REACT_APP_BOND_CONFIG_ID: ${REACT_APP_BOND_CONFIG_ID}
        # REACT_APP_BOND_CONFIG_VERSION: ${REACT_APP_BOND_CONFIG_VERSION}
        # REACT_APP_SHOW_DISCLAIMER: ${REACT_APP_SHOW_DISCLAIMER}
        # REACT_APP_PROJECT_ID: ${REACT_APP_PROJECT_ID}
        # REACT_APP_DAPP_NAME: ${REACT_APP_DAPP_NAME}
        # REACT_APP_DAPP_DESCRIPTION: ${REACT_APP_DAPP_DESCRIPTION}
        # REACT_APP_DAPP_URL: ${REACT_APP_DAPP_URL}
        # REACT_APP_DAPP_ICONS: ${REACT_APP_DAPP_ICONS}
    ports:
      - "5174:5174"
