/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../../../common";

export interface IExternalKycListManagementInterface extends utils.Interface {
  functions: {
    "addExternalKycList(address)": FunctionFragment;
    "getExternalKycListsCount()": FunctionFragment;
    "getExternalKycListsMembers(uint256,uint256)": FunctionFragment;
    "initialize_ExternalKycLists(address[])": FunctionFragment;
    "isExternalKycList(address)": FunctionFragment;
    "isExternallyGranted(address,uint8)": FunctionFragment;
    "removeExternalKycList(address)": FunctionFragment;
    "updateExternalKycLists(address[],bool[])": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "addExternalKycList"
      | "getExternalKycListsCount"
      | "getExternalKycListsMembers"
      | "initialize_ExternalKycLists"
      | "isExternalKycList"
      | "isExternallyGranted"
      | "removeExternalKycList"
      | "updateExternalKycLists"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addExternalKycList",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getExternalKycListsCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getExternalKycListsMembers",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize_ExternalKycLists",
    values: [string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "isExternalKycList",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "isExternallyGranted",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeExternalKycList",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateExternalKycLists",
    values: [string[], boolean[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "addExternalKycList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getExternalKycListsCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getExternalKycListsMembers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initialize_ExternalKycLists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isExternalKycList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isExternallyGranted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeExternalKycList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateExternalKycLists",
    data: BytesLike
  ): Result;

  events: {
    "AddedToExternalKycLists(address,address)": EventFragment;
    "ExternalKycListsUpdated(address,address[],bool[])": EventFragment;
    "RemovedFromExternalKycLists(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AddedToExternalKycLists"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ExternalKycListsUpdated"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "RemovedFromExternalKycLists"
  ): EventFragment;
}

export interface AddedToExternalKycListsEventObject {
  operator: string;
  kycList: string;
}
export type AddedToExternalKycListsEvent = TypedEvent<
  [string, string],
  AddedToExternalKycListsEventObject
>;

export type AddedToExternalKycListsEventFilter =
  TypedEventFilter<AddedToExternalKycListsEvent>;

export interface ExternalKycListsUpdatedEventObject {
  operator: string;
  kycLists: string[];
  actives: boolean[];
}
export type ExternalKycListsUpdatedEvent = TypedEvent<
  [string, string[], boolean[]],
  ExternalKycListsUpdatedEventObject
>;

export type ExternalKycListsUpdatedEventFilter =
  TypedEventFilter<ExternalKycListsUpdatedEvent>;

export interface RemovedFromExternalKycListsEventObject {
  operator: string;
  kycList: string;
}
export type RemovedFromExternalKycListsEvent = TypedEvent<
  [string, string],
  RemovedFromExternalKycListsEventObject
>;

export type RemovedFromExternalKycListsEventFilter =
  TypedEventFilter<RemovedFromExternalKycListsEvent>;

export interface IExternalKycListManagement extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IExternalKycListManagementInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addExternalKycList(
      _kycList: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    getExternalKycListsCount(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { externalKycListsCount_: BigNumber }>;

    getExternalKycListsMembers(
      _pageIndex: BigNumberish,
      _pageLength: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string[]] & { members_: string[] }>;

    initialize_ExternalKycLists(
      _kycLists: string[],
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    isExternalKycList(
      _kycList: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isExternallyGranted(
      _account: string,
      _kycStatus: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    removeExternalKycList(
      _kycList: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    updateExternalKycLists(
      _kycLists: string[],
      _actives: boolean[],
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  addExternalKycList(
    _kycList: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  getExternalKycListsCount(overrides?: CallOverrides): Promise<BigNumber>;

  getExternalKycListsMembers(
    _pageIndex: BigNumberish,
    _pageLength: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string[]>;

  initialize_ExternalKycLists(
    _kycLists: string[],
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  isExternalKycList(
    _kycList: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isExternallyGranted(
    _account: string,
    _kycStatus: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  removeExternalKycList(
    _kycList: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  updateExternalKycLists(
    _kycLists: string[],
    _actives: boolean[],
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    addExternalKycList(
      _kycList: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    getExternalKycListsCount(overrides?: CallOverrides): Promise<BigNumber>;

    getExternalKycListsMembers(
      _pageIndex: BigNumberish,
      _pageLength: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string[]>;

    initialize_ExternalKycLists(
      _kycLists: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    isExternalKycList(
      _kycList: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isExternallyGranted(
      _account: string,
      _kycStatus: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    removeExternalKycList(
      _kycList: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    updateExternalKycLists(
      _kycLists: string[],
      _actives: boolean[],
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {
    "AddedToExternalKycLists(address,address)"(
      operator?: string | null,
      kycList?: null
    ): AddedToExternalKycListsEventFilter;
    AddedToExternalKycLists(
      operator?: string | null,
      kycList?: null
    ): AddedToExternalKycListsEventFilter;

    "ExternalKycListsUpdated(address,address[],bool[])"(
      operator?: string | null,
      kycLists?: null,
      actives?: null
    ): ExternalKycListsUpdatedEventFilter;
    ExternalKycListsUpdated(
      operator?: string | null,
      kycLists?: null,
      actives?: null
    ): ExternalKycListsUpdatedEventFilter;

    "RemovedFromExternalKycLists(address,address)"(
      operator?: string | null,
      kycList?: null
    ): RemovedFromExternalKycListsEventFilter;
    RemovedFromExternalKycLists(
      operator?: string | null,
      kycList?: null
    ): RemovedFromExternalKycListsEventFilter;
  };

  estimateGas: {
    addExternalKycList(
      _kycList: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    getExternalKycListsCount(overrides?: CallOverrides): Promise<BigNumber>;

    getExternalKycListsMembers(
      _pageIndex: BigNumberish,
      _pageLength: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initialize_ExternalKycLists(
      _kycLists: string[],
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    isExternalKycList(
      _kycList: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isExternallyGranted(
      _account: string,
      _kycStatus: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    removeExternalKycList(
      _kycList: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    updateExternalKycLists(
      _kycLists: string[],
      _actives: boolean[],
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addExternalKycList(
      _kycList: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    getExternalKycListsCount(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getExternalKycListsMembers(
      _pageIndex: BigNumberish,
      _pageLength: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize_ExternalKycLists(
      _kycLists: string[],
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    isExternalKycList(
      _kycList: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isExternallyGranted(
      _account: string,
      _kycStatus: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    removeExternalKycList(
      _kycList: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    updateExternalKycLists(
      _kycLists: string[],
      _actives: boolean[],
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
