declare const meta: import("@storybook/types").ComponentAnnotations<import("@storybook/react/dist/types-0a347bb9").R, import("./InputController").InputControllerProps<import("react-hook-form").FieldValues>>;
export default meta;
export declare const NoValidations: import("@storybook/types").AnnotatedStoryFn<import("@storybook/react/dist/types-0a347bb9").R, import("./InputController").InputControllerProps<import("react-hook-form").FieldValues>>;
export declare const WithValidations: import("@storybook/types").AnnotatedStoryFn<import("@storybook/react/dist/types-0a347bb9").R, import("./InputController").InputControllerProps<import("react-hook-form").FieldValues>>;
export declare const ShowIsSuccess: import("@storybook/types").AnnotatedStoryFn<import("@storybook/react/dist/types-0a347bb9").R, import("./InputController").InputControllerProps<import("react-hook-form").FieldValues>>;
export declare const OnChangeCustom: import("@storybook/types").AnnotatedStoryFn<import("@storybook/react/dist/types-0a347bb9").R, import("./InputController").InputControllerProps<import("react-hook-form").FieldValues>>;
export declare const OnBlurCustom: import("@storybook/types").AnnotatedStoryFn<import("@storybook/react/dist/types-0a347bb9").R, import("./InputController").InputControllerProps<import("react-hook-form").FieldValues>>;
export declare const HideErrors: import("@storybook/types").AnnotatedStoryFn<import("@storybook/react/dist/types-0a347bb9").R, import("./InputController").InputControllerProps<import("react-hook-form").FieldValues>>;
export declare const WithDefaultValue: import("@storybook/types").AnnotatedStoryFn<import("@storybook/react/dist/types-0a347bb9").R, import("./InputController").InputControllerProps<import("react-hook-form").FieldValues>>;
export declare const IsClearable: import("@storybook/types").AnnotatedStoryFn<import("@storybook/react/dist/types-0a347bb9").R, import("./InputController").InputControllerProps<import("react-hook-form").FieldValues>>;
