/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IBond_,
  IBond_Interface,
} from "../../../../../../contracts/factory/ERC3643/interfaces/IBond.sol/IBond_";

const _abi = [
  {
    inputs: [],
    name: "getBondDetails",
    outputs: [
      {
        components: [
          {
            internalType: "bytes3",
            name: "currency",
            type: "bytes3",
          },
          {
            internalType: "uint256",
            name: "nominalValue",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "startingDate",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "maturityDate",
            type: "uint256",
          },
        ],
        internalType: "struct IBond_.BondDetailsData",
        name: "bondDetailsData_",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_couponID",
        type: "uint256",
      },
    ],
    name: "getCoupon",
    outputs: [
      {
        components: [
          {
            components: [
              {
                internalType: "uint256",
                name: "recordDate",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "executionDate",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "rate",
                type: "uint256",
              },
            ],
            internalType: "struct IBond_.Coupon",
            name: "coupon",
            type: "tuple",
          },
          {
            internalType: "uint256",
            name: "snapshotId",
            type: "uint256",
          },
        ],
        internalType: "struct IBond_.RegisteredCoupon",
        name: "registeredCoupon_",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getCouponCount",
    outputs: [
      {
        internalType: "uint256",
        name: "couponCount_",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getCouponDetails",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "couponFrequency",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "couponRate",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "firstCouponDate",
            type: "uint256",
          },
        ],
        internalType: "struct IBond_.CouponDetailsData",
        name: "couponDetails_",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_couponID",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_account",
        type: "address",
      },
    ],
    name: "getCouponFor",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "tokenBalance",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "rate",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "recordDate",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "executionDate",
            type: "uint256",
          },
          {
            internalType: "uint8",
            name: "decimals",
            type: "uint8",
          },
          {
            internalType: "bool",
            name: "recordDateReached",
            type: "bool",
          },
        ],
        internalType: "struct IBond_.CouponFor",
        name: "couponFor_",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_couponID",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_pageIndex",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_pageLength",
        type: "uint256",
      },
    ],
    name: "getCouponHolders",
    outputs: [
      {
        internalType: "address[]",
        name: "holders_",
        type: "address[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_couponID",
        type: "uint256",
      },
    ],
    name: "getTotalCouponHolders",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_tokenHolder",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "_partition",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "redeemAtMaturityByPartition",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "recordDate",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "executionDate",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "rate",
            type: "uint256",
          },
        ],
        internalType: "struct IBond_.Coupon",
        name: "_newCoupon",
        type: "tuple",
      },
    ],
    name: "setCoupon",
    outputs: [
      {
        internalType: "bool",
        name: "success_",
        type: "bool",
      },
      {
        internalType: "uint256",
        name: "couponID_",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_maturityDate",
        type: "uint256",
      },
    ],
    name: "updateMaturityDate",
    outputs: [
      {
        internalType: "bool",
        name: "success_",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IBond___factory {
  static readonly abi = _abi;
  static createInterface(): IBond_Interface {
    return new utils.Interface(_abi) as IBond_Interface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IBond_ {
    return new Contract(address, _abi, signerOrProvider) as IBond_;
  }
}
