// SPDX-License-Identifier: Apache-2.0

import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  atsSidebar: [
    "intro",
    {
      type: "category",
      label: "Getting Started",
      collapsed: true,
      link: {
        type: "doc",
        id: "getting-started/index",
      },
      items: ["getting-started/capabilities-overview", "getting-started/quick-start", "getting-started/full-setup"],
    },
    {
      type: "category",
      label: "User Guides",
      collapsed: true,
      link: {
        type: "doc",
        id: "user-guides/index",
      },
      items: [
        "user-guides/creating-equity",
        "user-guides/creating-bond",
        "user-guides/token-operations",
        "user-guides/updating-configuration",
        "user-guides/corporate-actions",
        "user-guides/managing-compliance",
        "user-guides/managing-external-kyc-lists",
        "user-guides/managing-external-control-lists",
        "user-guides/managing-external-pause-lists",
        "user-guides/hold-operations",
        "user-guides/clearing-operations",
        "user-guides/ssi-integration",
        "user-guides/roles-and-permissions",
      ],
    },
    {
      type: "category",
      label: "Developer Guides",
      collapsed: true,
      link: {
        type: "doc",
        id: "developer-guides/index",
      },
      items: [
        {
          type: "category",
          label: "SDK",
          collapsed: true,
          items: ["developer-guides/sdk-integration", "developer-guides/sdk-overview"],
        },
        {
          type: "category",
          label: "Smart Contracts",
          collapsed: true,
          link: {
            type: "doc",
            id: "developer-guides/contracts/index",
          },
          items: [
            {
              type: "category",
              label: "Understand",
              collapsed: true,
              items: [
                "developer-guides/contracts/overview",
                "developer-guides/contracts/architecture",
                "developer-guides/contracts/repository-structure",
                "developer-guides/contracts/core-concepts",
                "developer-guides/contracts/glossary",
              ],
            },
            {
              type: "category",
              label: "Build & Test",
              collapsed: true,
              items: ["developer-guides/contracts/getting-started", "developer-guides/contracts/testing"],
            },
            {
              type: "category",
              label: "Deploy",
              collapsed: true,
              items: [
                "developer-guides/contracts/deployment",
                "developer-guides/contracts/deployment-workflows",
                "developer-guides/contracts/checkpoints-and-recovery",
                "developer-guides/contracts/upgrading-configurations",
                "developer-guides/contracts/upgrading-infrastructure",
                "developer-guides/contracts/deployed-addresses",
              ],
            },
            {
              type: "category",
              label: "Extend",
              collapsed: true,
              items: [
                "developer-guides/contracts/adding-a-facet",
                "developer-guides/contracts/creating-an-asset-type",
                "developer-guides/contracts/managing-the-blr",
                "developer-guides/contracts/deploying-an-asset-proxy",
                "developer-guides/contracts/hash-codegen",
                "developer-guides/contracts/documenting-contracts",
              ],
            },
            {
              type: "category",
              label: "Operate & Safety",
              collapsed: true,
              items: [
                "developer-guides/contracts/roles-and-permissions",
                "developer-guides/contracts/scheduled-tasks-force-cancel",
              ],
            },
            {
              type: "category",
              label: "Reference",
              collapsed: true,
              items: [
                "developer-guides/contracts/erc-3643-compatibility",
                "developer-guides/contracts/downstream-deployment-utils",
              ],
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "API Documentation",
      collapsed: true,
      link: {
        type: "doc",
        id: "api/index",
      },
      items: [
        "api/sdk-reference",
        {
          type: "category",
          label: "Smart Contracts",
          collapsed: true,
          link: {
            type: "generated-index",
            title: "Smart Contracts API",
            description: "Auto-generated API documentation from NatSpec comments in the ATS smart contracts.",
          },
          items: [{ type: "autogenerated", dirName: "api/contracts" }],
        },
      ],
    },
  ],
};

export default sidebars;
