/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IBusinessLogicResolver___factory } from "./IBusinessLogicResolver___factory";
export { TRexIBusinessLogicResolver__factory } from "./TRexIBusinessLogicResolver__factory";
