/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IBond__factory } from "./IBond__factory";
export { IBondStorageWrapper__factory } from "./IBondStorageWrapper__factory";
