// SPDX-License-Identifier: Apache-2.0

// TEST-ONLY FILE: AssetMock domain configuration. Registers the union of every
// asset-class facet set (equity, bond, bondFixedRate, bondKpiLinkedRate, loan,
// loansPortfolio, depositToken) + MockDiamondCut under a single configId so
// tests can deploy one asset exposing every IAsset function.
//
// The facet union is built programmatically from per-type seed arrays that
// mirror each sibling createConfiguration.ts. Duplicates are removed via Set.
// DiamondFacet is swapped for MockDiamondCut.

import {
  ConfigurationData,
  ConfigurationError,
  OperationResult,
  createBatchConfiguration,
  DEFAULT_BATCH_SIZE,
  RetryOptions,
} from "@scripts/infrastructure";
import { BusinessLogicResolver } from "@contract-types";
import { ASSET_MOCK_CONFIG_ID } from "../constants";
import { atsRegistry } from "../atsRegistry";
import { getMockFacetDefinition } from "../initializeMock/mockFacetsRegistry";

// ── Per-type facet seeds (mirrors each sibling createConfiguration.ts) ──────

const EQUITY_FACETS = [
  "AccessControlFacet",
  "AllowanceFacet",
  "CapFacet",
  "CapByPartitionFacet",
  "ControlListFacet",
  "CorporateActionsFacet",
  "DiamondFacet",
  "CoreFacet",
  "TransferFacet",
  "CoreAdjustedFacet",
  "InitializerFacet",
  "CustomDataFacet",
  "FreezeFacet",
  "BatchFreezeFacet",
  "KycFacet",
  "PauseFacet",
  "BalanceTrackerFacet",
  "BalanceTrackerAdjustedFacet",
  "SnapshotsFacet",
  "SnapshotsByPartitionFacet",
  "SecurityHoldersAtSnapshotFacet",
  "HoldAtSnapshotFacet",
  "LockAtSnapshotByPartitionFacet",
  "FreezeAtSnapshotFacet",
  "FreezeAtSnapshotByPartitionFacet",
  "LockAtSnapshotFacet",
  "CoreAtSnapshotFacet",
  "BalanceTrackerByPartitionFacet",
  "BalanceTrackerAtSnapshotFacet",
  "BalanceTrackerAtSnapshotByPartitionFacet",
  "ClearingAtSnapshotFacet",
  "ClearingAtSnapshotByPartitionFacet",
  "HoldAtSnapshotByPartitionFacet",
  "MintByPartitionFacet",
  "ProtectedByPartitionFacet",
  "OperatorFacet",
  "TransferByPartitionFacet",
  "PartitionsFacet",
  "OperatorByPartitionFacet",
  "BurnByPartitionFacet",
  "DocumentationFacet",
  "ControllerFacet",
  "ERC20PermitFacet",
  "EIP712Facet",
  "NoncesFacet",
  "DeactivateFacet",
  "ERC20VotesFacet",
  "BatchControllerFacet",
  "BatchBurnFacet",
  "BatchMintFacet",
  "BatchTransferFacet",
  "RecoveryFacet",
  "IdentityFacet",
  "ComplianceFacet",
  "ComplianceByPartitionFacet",
  "MintFacet",
  "BurnFacet",
  "ClearingByPartitionFacet",
  "ProtectedClearingHoldByPartitionFacet",
  "ClearingHoldByPartitionFacet",
  "OperatorClearingHoldByPartitionFacet",
  "ClearingFacet",
  "OperatorClearingByPartitionFacet",
  "ProtectedClearingByPartitionFacet",
  "HoldFacet",
  "OperatorHoldByPartitionFacet",
  "ControllerHoldByPartitionFacet",
  "ControllerByPartitionFacet",
  "ProtectedHoldByPartitionFacet",
  "HoldByPartitionFacet",
  "ExternalControlListManagementFacet",
  "ExternalKycListManagementFacet",
  "ExternalPauseManagementFacet",
  "AdjustBalancesFacet",
  "ScheduledBalanceAdjustmentFacet",
  "DividendFacet",
  "DividendSecurityHoldersFacet",
  "LockFacet",
  "LockByPartitionFacet",
  "NominalValueFacet",
  "NominalValueAtSnapshotFacet",
  "ProtectedPartitionsFacet",
  "ScheduledCrossOrderedTasksFacet",
  "SecurityHoldersFacet",
  "SsiManagementFacet",
  "TransferAndLockFacet",
  "TransferAndLockByPartitionFacet",
  "VotingFacet",
  "VotingSecurityHoldersFacet",
  "InterestRateFacet",
  "ProceedRecipientsFacet",
];

const BOND_FACETS = [
  "AccessControlFacet",
  "CapFacet",
  "CapByPartitionFacet",
  "ControlListFacet",
  "CorporateActionsFacet",
  "DiamondFacet",
  "FreezeFacet",
  "BatchFreezeFacet",
  "KycFacet",
  "PauseFacet",
  "SnapshotsFacet",
  "SnapshotsByPartitionFacet",
  "SecurityHoldersAtSnapshotFacet",
  "HoldAtSnapshotFacet",
  "LockAtSnapshotByPartitionFacet",
  "FreezeAtSnapshotFacet",
  "FreezeAtSnapshotByPartitionFacet",
  "LockAtSnapshotFacet",
  "CoreAtSnapshotFacet",
  "BalanceTrackerFacet",
  "BalanceTrackerAdjustedFacet",
  "BalanceTrackerByPartitionFacet",
  "BalanceTrackerAtSnapshotFacet",
  "BalanceTrackerAtSnapshotByPartitionFacet",
  "ClearingAtSnapshotFacet",
  "ClearingAtSnapshotByPartitionFacet",
  "HoldAtSnapshotByPartitionFacet",
  "CoreFacet",
  "AllowanceFacet",
  "CoreAdjustedFacet",
  "InitializerFacet",
  "CustomDataFacet",
  "TransferFacet",
  "MintByPartitionFacet",
  "ProtectedByPartitionFacet",
  "OperatorFacet",
  "TransferByPartitionFacet",
  "PartitionsFacet",
  "OperatorByPartitionFacet",
  "BurnByPartitionFacet",
  "DocumentationFacet",
  "ControllerFacet",
  "ERC20PermitFacet",
  "EIP712Facet",
  "NoncesFacet",
  "DeactivateFacet",
  "ERC20VotesFacet",
  "BatchControllerFacet",
  "BatchBurnFacet",
  "BatchMintFacet",
  "BatchTransferFacet",
  "RecoveryFacet",
  "IdentityFacet",
  "ComplianceFacet",
  "ComplianceByPartitionFacet",
  "MintFacet",
  "BurnFacet",
  "ClearingByPartitionFacet",
  "ProtectedClearingHoldByPartitionFacet",
  "ClearingHoldByPartitionFacet",
  "OperatorClearingHoldByPartitionFacet",
  "ClearingFacet",
  "OperatorClearingByPartitionFacet",
  "ProtectedClearingByPartitionFacet",
  "HoldFacet",
  "OperatorHoldByPartitionFacet",
  "ControllerHoldByPartitionFacet",
  "ControllerByPartitionFacet",
  "ProtectedHoldByPartitionFacet",
  "HoldByPartitionFacet",
  "ExternalControlListManagementFacet",
  "ExternalKycListManagementFacet",
  "ExternalPauseManagementFacet",
  "AdjustBalancesFacet",
  "ScheduledBalanceAdjustmentFacet",
  "CouponFacet",
  "CouponSecurityHoldersFacet",
  "LockFacet",
  "LockByPartitionFacet",
  "MaturityFacet",
  "NominalValueFacet",
  "NominalValueAtSnapshotFacet",
  "ProceedRecipientsFacet",
  "ProtectedPartitionsFacet",
  "ScheduledCrossOrderedTasksFacet",
  "SecurityHoldersFacet",
  "CouponListingFacet",
  "SsiManagementFacet",
  "TransferAndLockFacet",
  "TransferAndLockByPartitionFacet",
  "InterestRateFacet",
  "MaturityByPartitionFacet",
  "PrincipalFacet",
];

const BOND_FIXED_RATE_FACETS = [
  "AccessControlFacet",
  "CapFacet",
  "CapByPartitionFacet",
  "ControlListFacet",
  "CorporateActionsFacet",
  "DiamondFacet",
  "FreezeFacet",
  "BatchFreezeFacet",
  "KycFacet",
  "PauseFacet",
  "BalanceTrackerFacet",
  "BalanceTrackerAdjustedFacet",
  "SnapshotsFacet",
  "SnapshotsByPartitionFacet",
  "SecurityHoldersAtSnapshotFacet",
  "HoldAtSnapshotFacet",
  "LockAtSnapshotByPartitionFacet",
  "FreezeAtSnapshotFacet",
  "FreezeAtSnapshotByPartitionFacet",
  "LockAtSnapshotFacet",
  "CoreAtSnapshotFacet",
  "BalanceTrackerByPartitionFacet",
  "BalanceTrackerAtSnapshotFacet",
  "BalanceTrackerAtSnapshotByPartitionFacet",
  "ClearingAtSnapshotFacet",
  "ClearingAtSnapshotByPartitionFacet",
  "HoldAtSnapshotByPartitionFacet",
  "CoreFacet",
  "AllowanceFacet",
  "CoreAdjustedFacet",
  "InitializerFacet",
  "CustomDataFacet",
  "TransferFacet",
  "MintByPartitionFacet",
  "ProtectedByPartitionFacet",
  "OperatorFacet",
  "TransferByPartitionFacet",
  "PartitionsFacet",
  "OperatorByPartitionFacet",
  "BurnByPartitionFacet",
  "DocumentationFacet",
  "ControllerFacet",
  "ERC20PermitFacet",
  "EIP712Facet",
  "NoncesFacet",
  "DeactivateFacet",
  "ERC20VotesFacet",
  "BatchControllerFacet",
  "BatchBurnFacet",
  "BatchMintFacet",
  "BatchTransferFacet",
  "RecoveryFacet",
  "IdentityFacet",
  "ComplianceFacet",
  "ComplianceByPartitionFacet",
  "MintFacet",
  "BurnFacet",
  "ClearingByPartitionFacet",
  "ProtectedClearingHoldByPartitionFacet",
  "ClearingHoldByPartitionFacet",
  "OperatorClearingHoldByPartitionFacet",
  "ClearingFacet",
  "OperatorClearingByPartitionFacet",
  "ProtectedClearingByPartitionFacet",
  "HoldFacet",
  "OperatorHoldByPartitionFacet",
  "ControllerHoldByPartitionFacet",
  "ControllerByPartitionFacet",
  "ProtectedHoldByPartitionFacet",
  "HoldByPartitionFacet",
  "ExternalControlListManagementFacet",
  "ExternalKycListManagementFacet",
  "ExternalPauseManagementFacet",
  "AdjustBalancesFacet",
  "ScheduledBalanceAdjustmentFacet",
  "LockFacet",
  "LockByPartitionFacet",
  "MaturityFacet",
  "NominalValueFacet",
  "NominalValueAtSnapshotFacet",
  "ProceedRecipientsFacet",
  "ProtectedPartitionsFacet",
  "ScheduledCrossOrderedTasksFacet",
  "SecurityHoldersFacet",
  "CouponListingFacet",
  "SsiManagementFacet",
  "TransferAndLockFacet",
  "TransferAndLockByPartitionFacet",
  "CouponSecurityHoldersFacet",
  "CouponFacet",
  "FixedRateFacet",
  "InterestRateFacet",
  "MaturityByPartitionFacet",
  "PrincipalFacet",
];

const BOND_KPI_LINKED_RATE_FACETS = [
  "AccessControlFacet",
  "AllowanceFacet",
  "CapFacet",
  "CapByPartitionFacet",
  "ControlListFacet",
  "CorporateActionsFacet",
  "DiamondFacet",
  "CoreFacet",
  "TransferFacet",
  "CoreAdjustedFacet",
  "InitializerFacet",
  "CustomDataFacet",
  "FreezeFacet",
  "BatchFreezeFacet",
  "KycFacet",
  "PauseFacet",
  "BalanceTrackerFacet",
  "BalanceTrackerAdjustedFacet",
  "SnapshotsFacet",
  "SnapshotsByPartitionFacet",
  "SecurityHoldersAtSnapshotFacet",
  "HoldAtSnapshotFacet",
  "LockAtSnapshotByPartitionFacet",
  "FreezeAtSnapshotFacet",
  "FreezeAtSnapshotByPartitionFacet",
  "LockAtSnapshotFacet",
  "CoreAtSnapshotFacet",
  "BalanceTrackerByPartitionFacet",
  "BalanceTrackerAtSnapshotFacet",
  "BalanceTrackerAtSnapshotByPartitionFacet",
  "ClearingAtSnapshotFacet",
  "ClearingAtSnapshotByPartitionFacet",
  "HoldAtSnapshotByPartitionFacet",
  "MintByPartitionFacet",
  "ProtectedByPartitionFacet",
  "OperatorFacet",
  "TransferByPartitionFacet",
  "PartitionsFacet",
  "OperatorByPartitionFacet",
  "BurnByPartitionFacet",
  "DocumentationFacet",
  "ControllerFacet",
  "ERC20PermitFacet",
  "EIP712Facet",
  "NoncesFacet",
  "DeactivateFacet",
  "ERC20VotesFacet",
  "BatchControllerFacet",
  "BatchBurnFacet",
  "BatchMintFacet",
  "BatchTransferFacet",
  "RecoveryFacet",
  "IdentityFacet",
  "ComplianceFacet",
  "ComplianceByPartitionFacet",
  "MintFacet",
  "BurnFacet",
  "ClearingByPartitionFacet",
  "ProtectedClearingHoldByPartitionFacet",
  "ClearingHoldByPartitionFacet",
  "OperatorClearingHoldByPartitionFacet",
  "ClearingFacet",
  "OperatorClearingByPartitionFacet",
  "ProtectedClearingByPartitionFacet",
  "HoldFacet",
  "OperatorHoldByPartitionFacet",
  "ControllerHoldByPartitionFacet",
  "ControllerByPartitionFacet",
  "ProtectedHoldByPartitionFacet",
  "HoldByPartitionFacet",
  "ExternalControlListManagementFacet",
  "ExternalKycListManagementFacet",
  "ExternalPauseManagementFacet",
  "AdjustBalancesFacet",
  "ScheduledBalanceAdjustmentFacet",
  "LockFacet",
  "LockByPartitionFacet",
  "MaturityFacet",
  "NominalValueFacet",
  "NominalValueAtSnapshotFacet",
  "ProceedRecipientsFacet",
  "ProtectedPartitionsFacet",
  "ScheduledCrossOrderedTasksFacet",
  "SecurityHoldersFacet",
  "CouponListingFacet",
  "SsiManagementFacet",
  "TransferAndLockFacet",
  "TransferAndLockByPartitionFacet",
  "CouponSecurityHoldersFacet",
  "CouponFacet",
  "KpiLinkedRateFacet",
  "KpisFacet",
  "InterestRateFacet",
  "MaturityByPartitionFacet",
  "PrincipalFacet",
];

const LOAN_FACETS = [
  "LoanFacet",
  "CouponFacet",
  "CouponSecurityHoldersFacet",
  "CouponListingFacet",
  "NominalValueFacet",
  "NominalValueAtSnapshotFacet",
  "AmortizationFacet",
  "ProceedRecipientsFacet",
  "AccessControlFacet",
  "BalanceTrackerFacet",
  "BalanceTrackerAdjustedFacet",
  "BalanceTrackerByPartitionFacet",
  "BalanceTrackerAtSnapshotFacet",
  "BalanceTrackerAtSnapshotByPartitionFacet",
  "ClearingAtSnapshotFacet",
  "ClearingAtSnapshotByPartitionFacet",
  "HoldAtSnapshotByPartitionFacet",
  "CapFacet",
  "CapByPartitionFacet",
  "ControlListFacet",
  "KycFacet",
  "SsiManagementFacet",
  "FreezeFacet",
  "BatchFreezeFacet",
  "PauseFacet",
  "CoreFacet",
  "AllowanceFacet",
  "TransferFacet",
  "CoreAdjustedFacet",
  "InitializerFacet",
  "CustomDataFacet",
  "ERC20PermitFacet",
  "EIP712Facet",
  "ERC20VotesFacet",
  "DocumentationFacet",
  "ControllerFacet",
  "OperatorFacet",
  "ProtectedByPartitionFacet",
  "MintByPartitionFacet",
  "TransferByPartitionFacet",
  "PartitionsFacet",
  "OperatorByPartitionFacet",
  "BurnByPartitionFacet",
  "RecoveryFacet",
  "IdentityFacet",
  "BatchControllerFacet",
  "BatchBurnFacet",
  "BatchMintFacet",
  "BatchTransferFacet",
  "ComplianceFacet",
  "ComplianceByPartitionFacet",
  "MintFacet",
  "BurnFacet",
  "HoldFacet",
  "OperatorHoldByPartitionFacet",
  "ControllerHoldByPartitionFacet",
  "ControllerByPartitionFacet",
  "ProtectedHoldByPartitionFacet",
  "HoldByPartitionFacet",
  "OperatorClearingByPartitionFacet",
  "ProtectedClearingByPartitionFacet",
  "ProtectedClearingHoldByPartitionFacet",
  "ClearingHoldByPartitionFacet",
  "OperatorClearingHoldByPartitionFacet",
  "ClearingFacet",
  "ClearingByPartitionFacet",
  "ScheduledCrossOrderedTasksFacet",
  "ExternalPauseManagementFacet",
  "ExternalControlListManagementFacet",
  "ExternalKycListManagementFacet",
  "DeactivateFacet",
  "DiamondFacet",
  "SnapshotsFacet",
  "SnapshotsByPartitionFacet",
  "SecurityHoldersAtSnapshotFacet",
  "HoldAtSnapshotFacet",
  "LockAtSnapshotByPartitionFacet",
  "FreezeAtSnapshotFacet",
  "FreezeAtSnapshotByPartitionFacet",
  "LockAtSnapshotFacet",
  "CoreAtSnapshotFacet",
  "CorporateActionsFacet",
  "SecurityHoldersFacet",
  "TransferAndLockFacet",
  "TransferAndLockByPartitionFacet",
  "LockFacet",
  "LockByPartitionFacet",
  "AdjustBalancesFacet",
  "ScheduledBalanceAdjustmentFacet",
  "ProtectedPartitionsFacet",
];

const LOANS_PORTFOLIO_FACETS = [
  "LoansPortfolioFacet",
  "AccessControlFacet",
  "AllowanceFacet",
  "CapFacet",
  "CapByPartitionFacet",
  "ControlListFacet",
  "CorporateActionsFacet",
  "DiamondFacet",
  "CoreFacet",
  "TransferFacet",
  "CoreAdjustedFacet",
  "InitializerFacet",
  "CustomDataFacet",
  "FreezeFacet",
  "BatchFreezeFacet",
  "KycFacet",
  "PauseFacet",
  "BalanceTrackerFacet",
  "BalanceTrackerAdjustedFacet",
  "SnapshotsFacet",
  "SnapshotsByPartitionFacet",
  "SecurityHoldersAtSnapshotFacet",
  "HoldAtSnapshotFacet",
  "LockAtSnapshotByPartitionFacet",
  "FreezeAtSnapshotFacet",
  "FreezeAtSnapshotByPartitionFacet",
  "LockAtSnapshotFacet",
  "CoreAtSnapshotFacet",
  "SsiManagementFacet",
  "BalanceTrackerByPartitionFacet",
  "BalanceTrackerAtSnapshotFacet",
  "BalanceTrackerAtSnapshotByPartitionFacet",
  "ClearingAtSnapshotFacet",
  "ClearingAtSnapshotByPartitionFacet",
  "HoldAtSnapshotByPartitionFacet",
  "MintByPartitionFacet",
  "ProtectedByPartitionFacet",
  "OperatorFacet",
  "TransferByPartitionFacet",
  "PartitionsFacet",
  "OperatorByPartitionFacet",
  "BurnByPartitionFacet",
  "DocumentationFacet",
  "ControllerFacet",
  "ERC20PermitFacet",
  "EIP712Facet",
  "NoncesFacet",
  "DeactivateFacet",
  "ERC20VotesFacet",
  "BatchControllerFacet",
  "BatchBurnFacet",
  "BatchMintFacet",
  "BatchTransferFacet",
  "RecoveryFacet",
  "IdentityFacet",
  "ComplianceFacet",
  "ComplianceByPartitionFacet",
  "MintFacet",
  "BurnFacet",
  "NominalValueFacet",
  "NominalValueAtSnapshotFacet",
  "HoldFacet",
  "OperatorHoldByPartitionFacet",
  "ControllerHoldByPartitionFacet",
  "ControllerByPartitionFacet",
  "ProtectedHoldByPartitionFacet",
  "HoldByPartitionFacet",
  "OperatorClearingByPartitionFacet",
  "ProtectedClearingByPartitionFacet",
  "ProtectedClearingHoldByPartitionFacet",
  "OperatorClearingHoldByPartitionFacet",
  "ClearingFacet",
  "ClearingByPartitionFacet",
  "ScheduledCrossOrderedTasksFacet",
  "CouponListingFacet",
  "ExternalPauseManagementFacet",
  "ExternalControlListManagementFacet",
  "ExternalKycListManagementFacet",
  "AdjustBalancesFacet",
  "ScheduledBalanceAdjustmentFacet",
  "LockFacet",
  "LockByPartitionFacet",
  "ProtectedPartitionsFacet",
  "SecurityHoldersFacet",
  "TransferAndLockFacet",
  "TransferAndLockByPartitionFacet",
];

const DEPOSIT_TOKEN_FACETS = [
  "AccessControlFacet",
  "DiamondFacet",
  "InitializerFacet",
  "ControlListFacet",
  "CoreFacet",
  "CapFacet",
  "AllowanceFacet",
  "BalanceTrackerFacet",
  "BalanceTrackerByPartitionFacet",
  "TransferFacet",
  "TransferByPartitionFacet",
  "MintFacet",
  "MintByPartitionFacet",
  "BurnFacet",
  "BurnByPartitionFacet",
  "ControllerFacet",
  "ControllerByPartitionFacet",
  "ControllerHoldByPartitionFacet",
  "OperatorFacet",
  "OperatorByPartitionFacet",
  "OperatorHoldByPartitionFacet",
  "OperatorClearingByPartitionFacet",
  "OperatorClearingHoldByPartitionFacet",
  "PartitionsFacet",
  "BatchControllerFacet",
  "BatchBurnFacet",
  "BatchMintFacet",
  "BatchTransferFacet",
  "BatchFreezeFacet",
  "FreezeFacet",
  "CapByPartitionFacet",
  "ClearingFacet",
  "ClearingByPartitionFacet",
  "ClearingHoldByPartitionFacet",
  "HoldFacet",
  "HoldByPartitionFacet",
  "ExternalControlListManagementFacet",
  "SecurityHoldersFacet",
  "DeactivateFacet",
  "DocumentationFacet",
  "CustomDataFacet",
  "NominalValueFacet",
  "PauseFacet",
];

// ── Build the deduplicated union ────────────────────────────────────────────

const ALL_ASSET_FACET_SETS = [
  EQUITY_FACETS,
  BOND_FACETS,
  BOND_FIXED_RATE_FACETS,
  BOND_KPI_LINKED_RATE_FACETS,
  LOAN_FACETS,
  LOANS_PORTFOLIO_FACETS,
  DEPOSIT_TOKEN_FACETS,
];

function buildAssetMockFacetList(): string[] {
  const facetSet = new Set<string>();
  for (const list of ALL_ASSET_FACET_SETS) {
    for (const name of list) {
      facetSet.add(name);
    }
  }
  const result = [...facetSet].sort();
  // Swap DiamondFacet → MockDiamondCut so the test asset exposes
  // forceNonOperational / forceFacetNotRegistered under RESOLVER_KEY_DIAMOND.
  const diamondIdx = result.indexOf("DiamondFacet");
  if (diamondIdx >= 0) {
    result[diamondIdx] = "MockDiamondCut";
  }
  return result;
}

// Cached at module load so the configuration function is fast.
const ASSET_MOCK_FACETS = buildAssetMockFacetList();

/**
 * TEST-ONLY: create the AssetMock configuration in BusinessLogicResolver.
 *
 * Registers the union of all asset-class facets (replacing DiamondFacet with
 * MockDiamondCut) under ASSET_MOCK_CONFIG_ID so a single diamond proxy exposes
 * every IAsset function plus the mock testing controls.
 *
 * @param blrContract        BusinessLogicResolver contract instance.
 * @param facetAddresses     Map of facet contract name → deployed address.
 * @param partialBatchDeploy Whether to mark batches as non-final.
 * @param batchSize          Number of facets per batch.
 * @param confirmations      Number of confirmations to wait for.
 */
export async function createAssetMockConfiguration(
  blrContract: BusinessLogicResolver,
  facetAddresses: Record<string, string>,
  partialBatchDeploy: boolean = false,
  batchSize: number = DEFAULT_BATCH_SIZE,
  confirmations: number = 0,
  retryOptions?: RetryOptions,
): Promise<OperationResult<ConfigurationData, ConfigurationError>> {
  const facets = ASSET_MOCK_FACETS.map((name) => {
    const facetDef = atsRegistry.getFacetDefinition(name) ?? getMockFacetDefinition(name);
    if (!facetDef?.resolverKey?.value) {
      throw new Error(`No resolver key found for facet: ${name}`);
    }
    return {
      facetName: name,
      resolverKey: facetDef.resolverKey.value,
      address: facetAddresses[name],
    };
  });

  return createBatchConfiguration(blrContract, {
    configurationId: ASSET_MOCK_CONFIG_ID,
    facets,
    partialBatchDeploy,
    batchSize,
    confirmations,
    retryOptions,
  });
}

/**
 * TEST-ONLY: return the list of facet names that the AssetMock configuration
 * will register. Useful for validation tests to check the resolved count.
 */
export function getAssetMockFacets(): string[] {
  return [...ASSET_MOCK_FACETS];
}
