export var calendarPartsList = [
    "input",
    "timeInput",
    "changeMonthButton",
    "dropdownPanel",
    "dropdownButton",
    "yearTitle",
    "footer",
    "header",
    "container",
    "headerTitle",
    "day",
    "month",
    "todayTooltip",
];
