/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IStaticFunctionSelectors_ } from "./IStaticFunctionSelectors_";
export type { TRexIStaticFunctionSelectors } from "./TRexIStaticFunctionSelectors";
