// SPDX-License-Identifier: Apache-2.0
pragma solidity >=0.8.0 <0.9.0;

/**
 * @notice ERC-7201 storage slot location for the nonce storage struct.
 * @dev Precalculated hash for the namespace `security.token.standard.storage.Nonce`.
 */
/// @custom:hash storage Nonce
bytes32 constant STORAGE_LOCATION_NONCE = 0x9752efd73e12c56ed1d4aebb7f98c3d8260f0d65c130c4c2ebd9d9c92d79a600;

/**
 * @notice Storage layout backing per-account nonces used to authorise signed off-chain operations.
 * @dev Anchored at the ERC-7201 namespace `security.token.standard.storage.Nonce`. New fields
 *      must be appended below the APPEND-ONLY marker to preserve upgrade safety.
 * @custom:storage-location erc7201:security.token.standard.storage.Nonce
 * @param nonces Mapping of composite account-key identifier hashes to sequential nonce values.
 */
struct NonceDataStorage {
    // ─── R1 Lifecycle (bool flags) ───────────────────────────
    // ─── R2 Packed scalars (uint8, bytes3, address, enum) ────
    // ─── R3 Single-slot scalars (uint256, bytes32, string) ───
    // ─── R4 Aggregates (mapping, array, EnumerableSet) ───────
    mapping(bytes32 => uint256) nonces;
    // ─── APPEND-ONLY ZONE BELOW ───
}

/**
 * @title NonceStorageWrapper
 * @notice Internal library exposing increment and read helpers for the per-account nonce store.
 * @dev Accesses ERC-7201 storage slot directly using inline assembly.
 * @author Asset Tokenization Studio Team
 */
library NonceStorageWrapper {
    /**
     * @notice Increments the nonce for `_account` under the specified `_key` by one.
     * @dev Wrapped in `unchecked` because monotonic, single-step increments cannot realistically
     *      overflow `uint256` for any account.
     * @param _account The address whose nonce is incremented.
     * @param _key Context key or action discriminator differentiating independent nonce sequences.
     */
    function setNonceFor(address _account, bytes32 _key) internal {
        unchecked {
            ++_nonceStorage().nonces[_buildNonceKey(_account, _key)];
        }
    }

    /**
     * @notice Returns the current nonce for `_account` under the specified `_key`.
     * @dev Reads the value mapped to the composite key generated by `_buildNonceKey`.
     * @param _account The address whose nonce is read.
     * @param _key Context key or action discriminator differentiating independent nonce sequences.
     * @return The current nonce value, zero if never set.
     */
    function getNonceFor(address _account, bytes32 _key) internal view returns (uint256) {
        return _nonceStorage().nonces[_buildNonceKey(_account, _key)];
    }

    /**
     * @notice Builds a composite key for identifying an account's nonce sequence.
     * @dev Returns an encoded address when `_key` is zero, or a keccak256 hash when non-zero.
     * @param _account The address associated with the nonce.
     * @param _key Context key or action discriminator differentiating independent nonce sequences.
     * @return The 32-byte identifier key used for storage lookup.
     */
    function _buildNonceKey(address _account, bytes32 _key) private pure returns (bytes32) {
        return _key == bytes32(0) ? bytes32(uint256(uint160(_account))) : keccak256(abi.encode(_account, _key));
    }

    /**
     * @notice Returns the storage pointer for the Nonce namespace.
     * @dev Resolves the ERC-7201 slot via inline assembly to obtain a struct reference at
     *      `STORAGE_LOCATION_NONCE`.
     * @return nonces_ Storage reference to the `NonceDataStorage` struct.
     */
    function _nonceStorage() private pure returns (NonceDataStorage storage nonces_) {
        bytes32 position = STORAGE_LOCATION_NONCE;
        // solhint-disable-next-line no-inline-assembly
        assembly {
            nonces_.slot := position
        }
    }
}
