// SPDX-License-Identifier: Apache-2.0

/**
 * Generate TypeScript registry code from contract metadata.
 *
 * @module tools/generators/registryGenerator
 */

import { ContractMetadata } from '../scanner/metadataExtractor'

/**
 * Generate complete registry TypeScript code.
 *
 * @param facets - Array of facet metadata
 * @param infrastructure - Array of infrastructure contract metadata
 * @returns TypeScript source code
 */
export function generateRegistry(
    facets: ContractMetadata[],
    infrastructure: ContractMetadata[]
): string {
    const header = generateHeader(facets.length, infrastructure.length)
    const facetRegistry = generateFacetRegistry(facets)
    const contractRegistry = generateContractRegistry(infrastructure)
    const constants = generateConstants()

    return `${header}\n\n${facetRegistry}\n\n${contractRegistry}\n\n${constants}\n`
}

/**
 * Generate file header with imports and comments.
 *
 * @param facetCount - Number of facets
 * @param infrastructureCount - Number of infrastructure contracts
 * @returns Header code
 */
function generateHeader(
    facetCount: number,
    infrastructureCount: number
): string {
    return `// SPDX-License-Identifier: Apache-2.0

/**
 * AUTO-GENERATED Contract Registry
 *
 * This file is automatically generated by the registry generation tool.
 * ! DO NOT EDIT MANUALLY - Changes will be overwritten.
 *
 * To regenerate: npm run generate:registry
 * To customize: Edit registry.overrides.ts
 *
 * Generated: ${new Date().toISOString()}
 * Facets: ${facetCount}
 * Infrastructure: ${infrastructureCount}
 *
 * @module infrastructure/registry.generated
 */

import { FacetDefinition, ContractDefinition } from '@scripts/infrastructure/types'`
}

/**
 * Generate FACET_REGISTRY constant.
 *
 * @param facets - Array of facet metadata
 * @returns TypeScript code for FACET_REGISTRY
 */
function generateFacetRegistry(facets: ContractMetadata[]): string {
    // Sort facets alphabetically for deterministic output
    const sortedFacets = [...facets].sort((a, b) =>
        a.name.localeCompare(b.name)
    )

    const entries = sortedFacets.map((facet) => generateFacetEntry(facet))

    return `/**
 * Registry of all facet contracts.
 *
 * Total facets: ${facets.length}
 */
export const FACET_REGISTRY: Record<string, FacetDefinition> = {
${entries.join(',\n\n')}
}`
}

/**
 * Generate single facet registry entry.
 *
 * SIMPLIFIED (2025-10-03): Only generates name and description.
 * Removed unused metadata fields that provided zero deployment value.
 *
 * @param facet - Facet metadata
 * @returns TypeScript object literal
 */
function generateFacetEntry(facet: ContractMetadata): string {
    return `    ${facet.name}: {
        name: '${facet.name}',
        description: '${facet.description}',
    }`
}

/**
 * Generate CONTRACT_REGISTRY constant.
 *
 * @param infrastructure - Array of infrastructure contract metadata
 * @returns TypeScript code for CONTRACT_REGISTRY
 */
function generateContractRegistry(infrastructure: ContractMetadata[]): string {
    const sortedContracts = [...infrastructure].sort((a, b) =>
        a.name.localeCompare(b.name)
    )

    const entries = sortedContracts.map((contract) =>
        generateContractEntry(contract)
    )

    return `/**
 * Registry of non-facet infrastructure contracts.
 *
 * Total contracts: ${infrastructure.length}
 */
export const CONTRACT_REGISTRY: Record<string, ContractDefinition> = {
${entries.join(',\n\n')}
}`
}

/**
 * Generate single contract registry entry.
 *
 * SIMPLIFIED (2025-10-03): Only generates name and description.
 *
 * @param contract - Contract metadata
 * @returns TypeScript object literal
 */
function generateContractEntry(contract: ContractMetadata): string {
    return `    ${contract.name}: {
        name: '${contract.name}',
        description: '${contract.description}',
    }`
}

/**
 * Generate constants section (roles).
 *
 * @returns TypeScript constants code
 */
function generateConstants(): string {
    return `/**
 * Common role identifiers.
 */
export const ROLES = {
    DEFAULT_ADMIN_ROLE:
        '0x0000000000000000000000000000000000000000000000000000000000000000',
    CONTROLLER_ROLE: 'CONTROLLER_ROLE',
    ISSUER_ROLE: 'ISSUER_ROLE',
    CORPORATE_ACTION_ROLE: 'CORPORATE_ACTION_ROLE',
    KYC_ROLE: 'KYC_ROLE',
    PAUSE_ROLE: 'PAUSE_ROLE',
    CONTROL_LIST_ROLE: 'CONTROL_LIST_ROLE',
} as const`
}

/**
 * Generate summary statistics.
 *
 * @param facets - Array of facet metadata
 * @param infrastructure - Array of infrastructure metadata
 * @returns Summary object
 */
export function generateSummary(
    facets: ContractMetadata[],
    infrastructure: ContractMetadata[]
): {
    totalFacets: number
    totalInfrastructure: number
    byCategory: Record<string, number>
    byLayer: Record<number, number>
    withTimeTravel: number
    withRoles: number
} {
    const byCategory: Record<string, number> = {}
    const byLayer: Record<number, number> = {}
    let withTimeTravel = 0
    let withRoles = 0

    for (const facet of facets) {
        byCategory[facet.category] = (byCategory[facet.category] || 0) + 1
        byLayer[facet.layer] = (byLayer[facet.layer] || 0) + 1
        if (facet.hasTimeTravel) withTimeTravel++
        if (facet.roles.length > 0) withRoles++
    }

    return {
        totalFacets: facets.length,
        totalInfrastructure: infrastructure.length,
        byCategory,
        byLayer,
        withTimeTravel,
        withRoles,
    }
}
