/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IFactory___factory } from "./IFactory___factory";
export { TRexIFactory__factory } from "./TRexIFactory__factory";
