name: "202: [FLOW] MP Lint and Format"

on:
  pull_request:
    paths:
      - "packages/mass-payout/**"
      - "apps/mass-payout/**"
      - "package.json"
      - "eslint.config.mjs"
      - "prettier.config.mjs"
      - ".prettierignore"
      - "solhint.config.js"
      - ".github/workflows/200-call-lint-format.yaml"
      - ".github/workflows/202-flow-mp-lint.yaml"

jobs:
  lint-and-format:
    uses: ./.github/workflows/200-call-lint-format.yaml
