name: Tests
on:
  pull_request:
  push:
    branches: [main]
jobs:
  test-node:
    name: testing
    runs-on: token-studio-linux-medium
    env:
      NODE_OPTIONS: "--max-old-space-size=32768"
    permissions:
      contents: read
    
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f086349bfa2bd1361f7909c78558e816508cdc10 # v2.8.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29

      - name: Setup NodeJS Environment
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8
        with:
          node-version: 18.x      
      
      - name: Cache npm dependencies
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies Contracts
        run: |
          npm ci
          npm run compile:force
        working-directory: contracts

      - name: Install dependencies SDK
        run: |
          npm ci
          npm run build
        working-directory: sdk

      - name: Install Yarn
        run: npm install -g yarn@1.22.19
      
      - name: Install dependencies web
        run: yarn install
        working-directory: web

      - name: Create .env file in SDK
        run: |
          touch .env
          echo "CLIENT_PRIVATE_KEY_ECDSA_1='${{ secrets.CLIENT_PRIVATE_KEY_ECDSA_1 }}'" >> .env
          echo "CLIENT_PUBLIC_KEY_ECDSA_1='${{ secrets.CLIENT_PUBLIC_KEY_ECDSA_1 }}'" >> .env
          echo "CLIENT_ACCOUNT_ID_ECDSA_1='${{ secrets.CLIENT_ACCOUNT_ID_ECDSA_1 }}'" >> .env
          echo "CLIENT_EVM_ADDRESS_ECDSA_1='${{ secrets.CLIENT_EVM_ADDRESS_ECDSA_1 }}'" >> .env
          echo "CLIENT_PRIVATE_KEY_ECDSA_2='${{ secrets.CLIENT_PRIVATE_KEY_ECDSA_2 }}'" >> .env
          echo "CLIENT_PUBLIC_KEY_ECDSA_2='${{ secrets.CLIENT_PUBLIC_KEY_ECDSA_2 }}'" >> .env
          echo "CLIENT_ACCOUNT_ID_ECDSA_2='${{ secrets.CLIENT_ACCOUNT_ID_ECDSA_2 }}'" >> .env
          echo "CLIENT_EVM_ADDRESS_ECDSA_2='${{ secrets.CLIENT_EVM_ADDRESS_ECDSA_2 }}'" >> .env
          echo "FACTORY_ADDRESS='${{ secrets.FACTORY_ADDRESS }}'"  >> .env
          echo "RESOLVER_ADDRESS='${{ secrets.RESOLVER_ADDRESS }}'"  >> .env
          echo "BUSINESS_LOGIC_KEYS_COMMON='${{ secrets.BUSINESS_LOGIC_KEYS_COMMON }}'"  >> .env
          echo "BUSINESS_LOGIC_KEYS_EQUITY='${{ secrets.BUSINESS_LOGIC_KEYS_EQUITY }}'"  >> .env
          echo "BUSINESS_LOGIC_KEYS_BOND='${{ secrets.BUSINESS_LOGIC_KEYS_BOND }}'"  >> .env
        working-directory: sdk

      - name: Create .env file in WEB
        run: |
          touch .env
          echo "REACT_APP_MIRROR_NODE='https://testnet.mirrornode.hedera.com/api/v1/'"  >> .env
          echo "REACT_APP_RPC_NODE='https://testnet.hashio.io/api'"  >> .env
          echo "REACT_APP_RPC_RESOLVER='${{ secrets.REACT_APP_RPC_RESOLVER }}'"  >> .env
          echo "REACT_APP_RPC_FACTORY='${{ secrets.REACT_APP_RPC_FACTORY }}'"  >> .env
          echo "REACT_APP_BUSINESS_LOGIC_KEYS_COMMON='${{ secrets.REACT_APP_BUSINESS_LOGIC_KEYS_COMMON }}'"  >> .env
          echo "REACT_APP_BUSINESS_LOGIC_KEYS_EQUITY='${{ secrets.REACT_APP_BUSINESS_LOGIC_KEYS_EQUITY }}'"  >> .env
          echo "REACT_APP_BUSINESS_LOGIC_KEYS_BOND='${{ secrets.REACT_APP_BUSINESS_LOGIC_KEYS_BOND }}'"  >> .env
          echo "REACT_APP_SHOW_DISCLAIMER='true'"  >> .env
        working-directory: web

      - name: Test web
        run: |
          npm run test
          npm run cleanCache
        working-directory: web

      - name: Test Contracts
        run: |
          npm run test
          npm run cleanCache
        working-directory: contracts

      - name: Test sdk
        run: |
          npm run test
          npm run cleanCache
        working-directory: sdk

      - name: Upload coverage report
        if: ${{ !cancelled() && always() }}
        uses: codecov/codecov-action@e28ff129e5465c2c0dcc6f003fc735cb6ae0c673
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
