name: Tests
on:
  pull_request:
  push:
    branches: [main]

jobs:
  test-node:
    name: testing
    runs-on: token-studio-linux-large
    env:
      NODE_OPTIONS: "--max-old-space-size=32768"
    permissions:
      contents: read

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f086349bfa2bd1361f7909c78558e816508cdc10 # v2.8.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29

      - name: Setup NodeJS Environment
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8
        with:
          node-version: 18.x

      - name: Install dependencies Contracts
        working-directory: contracts
        run: |
          npm ci
          npm run compile:force

      - name: Test Contracts
        working-directory: contracts
        run: npm run test

      - name: Install dependencies SDK
        working-directory: sdk
        run: |
          npm ci
          npm run build

      - name: Install Yarn
        run: npm install -g yarn@1.22.22

      #      # No tests for UI components yet
      #      - name: Install dependencies UI Components
      #        working-directory: uiComponents
      #        run: yarn install

      - name: Install dependencies web
        working-directory: web
        run: yarn install

      - name: Build web
        working-directory: web
        run: yarn build

      - name: Create .env file in SDK
        working-directory: sdk
        run: |
          touch .env
          echo "CLIENT_PRIVATE_KEY_ECDSA_1=${{ secrets.CLIENT_PRIVATE_KEY_ECDSA_1 }}" >> .env
          echo "CLIENT_PUBLIC_KEY_ECDSA_1=${{ secrets.CLIENT_PUBLIC_KEY_ECDSA_1 }}" >> .env
          echo "CLIENT_ACCOUNT_ID_ECDSA_1=${{ secrets.CLIENT_ACCOUNT_ID_ECDSA_1 }}" >> .env
          echo "CLIENT_EVM_ADDRESS_ECDSA_1=${{ secrets.CLIENT_EVM_ADDRESS_ECDSA_1 }}" >> .env
          echo "CLIENT_PRIVATE_KEY_ECDSA_2=${{ secrets.CLIENT_PRIVATE_KEY_ECDSA_2 }}" >> .env
          echo "CLIENT_PUBLIC_KEY_ECDSA_2=${{ secrets.CLIENT_PUBLIC_KEY_ECDSA_2 }}" >> .env
          echo "CLIENT_ACCOUNT_ID_ECDSA_2=${{ secrets.CLIENT_ACCOUNT_ID_ECDSA_2 }}" >> .env
          echo "CLIENT_EVM_ADDRESS_ECDSA_2=${{ secrets.CLIENT_EVM_ADDRESS_ECDSA_2 }}" >> .env
          echo "FACTORY_ADDRESS='0.0.5383498'"  >> .env
          echo "RESOLVER_ADDRESS='0.0.5383403'"  >> .env
          echo "FIREBLOCKS_HEDERA_ACCOUNT_ID=${{ secrets.FIREBLOCKS_HEDERA_ACCOUNT_ID }}" >> .env
          echo "FIREBLOCKS_HEDERA_PUBLIC_KEY=${{ secrets.FIREBLOCKS_HEDERA_PUBLIC_KEY }}" >> .env
          echo "DFNS_HEDERA_ACCOUNT_ID=${{ secrets.DFNS_HEDERA_ACCOUNT_ID }}" >> .env
          echo "DFNS_WALLET_PUBLIC_KEY=${{ secrets.DFNS_WALLET_PUBLIC_KEY }}" >> .env
          echo "AWS_KMS_HEDERA_ACCOUNT_ID=${{ secrets.AWS_KMS_HEDERA_ACCOUNT_ID }}" >> .env
          echo "AWS_KMS_HEDERA_PUBLIC_KEY=${{ secrets.AWS_KMS_HEDERA_PUBLIC_KEY }}" >> .env
      - name: Create .env file in WEB
        working-directory: web
        run: |
          touch .env
          echo "REACT_APP_MIRROR_NODE='https://testnet.mirrornode.hedera.com/api/v1/'"  >> .env
          echo "REACT_APP_RPC_NODE='https://testnet.hashio.io/api'"  >> .env
          echo "REACT_APP_RPC_RESOLVER='0.0.5383403'"  >> .env
          echo "REACT_APP_RPC_FACTORY='0.0.5383498'"  >> .env
          echo "REACT_APP_EQUITY_CONFIG_ID='0x0000000000000000000000000000000000000000000000000000000000000001'" >> .env
          echo "REACT_APP_EQUITY_CONFIG_VERSION='0'" >> .env
          echo "REACT_APP_BOND_CONFIG_ID='0x0000000000000000000000000000000000000000000000000000000000000002'" >> .env
          echo "REACT_APP_BOND_CONFIG_VERSION='0'" >> .env
          echo "REACT_APP_SHOW_DISCLAIMER='true'"  >> .env
          echo "REACT_APP_PROJECT_ID=${{ secrets.REACT_APP_PROJECT_ID }}"  >> .env
          echo "REACT_APP_DAPP_NAME='StableCoin'"  >> .env
          echo "REACT_APP_DAPP_DESCRIPTION='StableCoin is a decentralized stablecoin platform built on Hedera Hashgraph.'"  >> .env
          echo "REACT_APP_DAPP_URL='https://wc.hgraph.app/'"  >> .env
          echo "REACT_APP_DAPP_ICONS=['https://stablecoinstudio.com/static/media/hedera-hbar-logo.4fd73fb360de0fc15d378e0c3ebe6c80.svg']"  >> .env

      - name: Test web
        working-directory: web
        run: npm run test

      - name: Test sdk
        working-directory: sdk
        run: npm run test

      #      # No tests for UI components yet
      #      - name: Test UI Components
      #        working-directory: uiComponents
      #        run: ${{ steps.cgroup.outputs.exec }} npm run test

      - name: Upload coverage report
        if: ${{ !cancelled() && always() }}
        uses: codecov/codecov-action@e28ff129e5465c2c0dcc6f003fc735cb6ae0c673
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
