name: Tests
on:
  pull_request:
  push:
    branches: [main]

jobs:
  test-node:
    name: testing
    runs-on: token-studio-linux-large
    env:
      NODE_OPTIONS: "--max-old-space-size=32768"
      CLIENT_PRIVATE_KEY_ECDSA_1: ${{ secrets.CLIENT_PRIVATE_KEY_ECDSA_1 }}
      CLIENT_PUBLIC_KEY_ECDSA_1: ${{ secrets.CLIENT_PUBLIC_KEY_ECDSA_1 }}
      CLIENT_ACCOUNT_ID_ECDSA_1: ${{ secrets.CLIENT_ACCOUNT_ID_ECDSA_1 }}
      CLIENT_EVM_ADDRESS_ECDSA_1: ${{ secrets.CLIENT_EVM_ADDRESS_ECDSA_1 }}
      CLIENT_PRIVATE_KEY_ECDSA_2: ${{ secrets.CLIENT_PRIVATE_KEY_ECDSA_2 }}
      CLIENT_PUBLIC_KEY_ECDSA_2: ${{ secrets.CLIENT_PUBLIC_KEY_ECDSA_2 }}
      CLIENT_ACCOUNT_ID_ECDSA_2: ${{ secrets.CLIENT_ACCOUNT_ID_ECDSA_2 }}
      CLIENT_EVM_ADDRESS_ECDSA_2: ${{ secrets.CLIENT_EVM_ADDRESS_ECDSA_2 }}
      FACTORY_ADDRESS: "0.0.5383498"
      RESOLVER_ADDRESS: "0.0.5383403"
      FIREBLOCKS_HEDERA_ACCOUNT_ID: ${{ secrets.FIREBLOCKS_HEDERA_ACCOUNT_ID }}
      FIREBLOCKS_HEDERA_PUBLIC_KEY: ${{ secrets.FIREBLOCKS_HEDERA_PUBLIC_KEY }}
      DFNS_HEDERA_ACCOUNT_ID: ${{ secrets.DFNS_HEDERA_ACCOUNT_ID }}
      DFNS_WALLET_PUBLIC_KEY: ${{ secrets.DFNS_WALLET_PUBLIC_KEY }}
      AWS_KMS_HEDERA_ACCOUNT_ID: ${{ secrets.AWS_KMS_HEDERA_ACCOUNT_ID }}
      AWS_KMS_HEDERA_PUBLIC_KEY: ${{ secrets.AWS_KMS_HEDERA_PUBLIC_KEY }}
      REACT_APP_MIRROR_NODE: "https://testnet.mirrornode.hedera.com/api/v1/"
      REACT_APP_RPC_NODE: "https://testnet.hashio.io/api"
      REACT_APP_RPC_RESOLVER: "0.0.5383403"
      REACT_APP_RPC_FACTORY: "0.0.5383498"
      REACT_APP_EQUITY_CONFIG_ID: "0x0000000000000000000000000000000000000000000000000000000000000001"
      REACT_APP_EQUITY_CONFIG_VERSION: "0"
      REACT_APP_BOND_CONFIG_ID: "0x0000000000000000000000000000000000000000000000000000000000000002"
      REACT_APP_BOND_CONFIG_VERSION: "0"
      REACT_APP_SHOW_DISCLAIMER: "true"
      REACT_APP_PROJECT_ID: ${{ secrets.REACT_APP_PROJECT_ID }}
      REACT_APP_DAPP_NAME: "StableCoin"
      REACT_APP_DAPP_DESCRIPTION: "StableCoin is a decentralized stablecoin platform built on Hedera Hashgraph."
      REACT_APP_DAPP_URL: "https://wc.hgraph.app/"
      REACT_APP_DAPP_ICONS: "['https://stablecoinstudio.com/static/media/hedera-hbar-logo.4fd73fb360de0fc15d378e0c3ebe6c80.svg']"
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    
    permissions:
      contents: read

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f086349bfa2bd1361f7909c78558e816508cdc10 # v2.8.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29

      - name: Setup NodeJS Environment
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8
        with:
          node-version: 18.x

      - name: Install dependencies Contracts
        working-directory: contracts
        run: |
          npm ci
          npm run compile:force

      - name: Test Contracts
        working-directory: contracts
        run: npm run test

      - name: Install dependencies SDK
        working-directory: sdk
        run: |
          npm ci
          npm run build

      - name: Install Yarn
        run: npm install -g yarn@1.22.22

      #      # No tests for UI components yet
      #      - name: Install dependencies UI Components
      #        working-directory: uiComponents
      #        run: yarn install

      - name: Install dependencies web
        working-directory: web
        run: yarn install

      - name: Build web
        working-directory: web
        run: yarn build

      - name: Test web
        working-directory: web
        run: npm run test

      - name: Test sdk
        working-directory: sdk
        run: npm run test

      #      # No tests for UI components yet
      #      - name: Test UI Components
      #        working-directory: uiComponents
      #        run: ${{ steps.cgroup.outputs.exec }} npm run test

      - name: Upload coverage report
        if: ${{ !cancelled() && always() }}
        uses: codecov/codecov-action@e28ff129e5465c2c0dcc6f003fc735cb6ae0c673